### ISSUE TITLE
Installation fails to install components correctly

### ISSUE THREAD

**Issue by kiwihansen** [Puzzlepart/prosjektportalen365-bygganlegg#4]
**Describe the bug**

**To Reproduce**

1. Install PP365 1.2.7 on a site collection
2. Install PP365 Bygg og Anlegg
3. Check term store, fasesjekkliste_bygg, fasesjekkliste_anlegg, planneroppgaver_bygg, planneroppgaver_anlegg etc

**Expected behavior**
After installation, Term Store should be updated to add new term sets for Bygg and Anlegg. Lists mentioned above should have columns specifying which phase each task belongs to. Unable to complete manual step listed in installation instructions.

**Screenshots**
![image](https://user-images.githubusercontent.com/69144808/119955343-42b89e00-bfa0-11eb-9958-82ba0e42f27b.png)
![image](https://user-images.githubusercontent.com/69144808/119955477-5f54d600-bfa0-11eb-88df-c9de7e991d64.png)

**About your setup**

- Browser - Edge
- Installed version - PP365 1.2.7 + BA365 1.0.1

**Additional context**
No errors reported during installation. Nothing of note found in logs to detail what could have gone wrong.
Added log file.

[Install_Log.txt](https://github.com/Puzzlepart/prosjektportalen365-bygganlegg/files/6559456/Install_Log.txt)

**Comment by olemp** [comment]
Confirmed that there's something weird with the Portfolio PnP template. It doesn't do anything.

![image](https://user-images.githubusercontent.com/7606007/119963248-2a4c8180-bfa8-11eb-841a-5a6150ff0f01.png)

cc @tarjeieo @kiwihansen

**Comment by kiwihansen** [comment]
@olemp Should I set up a clean site collection to install on, or should I just use the -Upgrade flag?

**Comment by olemp** [comment]
> @olemp Should I set up a clean site collection to install on, or should I just use the -Upgrade flag?

Try first with -Upgrade flag.

**Comment by kiwihansen** [comment]
Looks promising so far:
![image](https://user-images.githubusercontent.com/69144808/119968468-cc229d00-bfad-11eb-8dbe-a2874a2a7794.png)
Doesn't look like it managed to fix the lists, it just adds the columns, but did not update the list items.
![image](https://user-images.githubusercontent.com/69144808/119970267-ccbc3300-bfaf-11eb-95f6-d99e6298e062.png)
![image](https://user-images.githubusercontent.com/69144808/119970290-d180e700-bfaf-11eb-9abe-fe31200a92f4.png)
Maybe I should have deleted these before running the new version then.

Provisioning does seem to work though:
![image](https://user-images.githubusercontent.com/69144808/119970468-0c831a80-bfb0-11eb-9518-87c34a1ca97a.png)
![image](https://user-images.githubusercontent.com/69144808/119970703-5966f100-bfb0-11eb-8cc9-5f8067a37705.png)

**Comment by kiwihansen** [comment]
I am unable to delete the lists that are missing column values. Any tips? @olemp

**Comment by kiwihansen** [comment]
Testing a clean install, just to be sure everthing is working.

**Comment by olemp** [comment]
> Testing a clean install, just to be sure everthing is working.

Yes, do a clean install.

**Comment by kiwihansen** [comment]
@olemp @pzljanb 

After clean install:
![image](https://user-images.githubusercontent.com/69144808/119984301-88d22980-bfc1-11eb-816f-2346f76049db.png)
![image](https://user-images.githubusercontent.com/69144808/119984320-8e2f7400-bfc1-11eb-8e8b-59523d269a69.png)
![image](https://user-images.githubusercontent.com/69144808/119984329-91c2fb00-bfc1-11eb-9b7c-309f19334517.png)
![image](https://user-images.githubusercontent.com/69144808/119984346-95ef1880-bfc1-11eb-9960-9de24e90bd28.png)
![image](https://user-images.githubusercontent.com/69144808/119984406-a56e6180-bfc1-11eb-8c09-64f24768d719.png)
![image](https://user-images.githubusercontent.com/69144808/119984437-ad2e0600-bfc1-11eb-9d94-4476983e5558.png)
![image](https://user-images.githubusercontent.com/69144808/119984452-b1f2ba00-bfc1-11eb-9be4-b4d90d2e4c7a.png)


I think we can give this version a clean bill of health!
